language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - cmake
      - gcc-4.8
matrix:
  include:
    - compiler: gcc
      env:
        CPP14_FLAG=" --verbose "
    - compiler: clang
      env:
        CPP14_FLAG="-std=c++1y"
script: ./.travis.build
