language: cpp
sudo: false
addons:
  apt:
    packages:
      - cmake
matrix:
  include:
    - compiler: gcc
      env:
        CPP14_FLAG=" --verbose "
    - compiler: clang
      env:
        CPP14_FLAG="-std=c++1y"
script: ./.travis.build
